// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://digtqrdxrpltuyfoapbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpZ3RxcmR4cnBsdHV5Zm9hcGJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyOTk1MjYsImV4cCI6MjA2NDg3NTUyNn0.SfOGnuq9hGrc2N9t26JKfM6q3dIoGHhaZ5_mAxY9t0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);